framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: fanout

        routing:
            # Route your messages to the transports
            'App\Message\PostMessage': amqp
            'App\Message\PatchMessage': amqp
            'App\Message\DeleteMessage': amqp
